<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PCMonitor.Core\PCMonitor.Core.csproj" />
    <ProjectReference Include="..\PCMonitor.Windows\PCMonitor.Windows.csproj" />
    <ProjectReference Include="..\PCMonitor.Notifications\PCMonitor.Notifications.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Product>PCNotify</Product>
    <Title>PCNotify - 电脑监控与手机极速推送守护程序</Title>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\app.ico" />
  </ItemGroup>

</Project>